# Generated by Django 3.2.4 on 2021-06-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('pro_img', models.ImageField(upload_to='product_images')),
                ('price', models.CharField(max_length=10)),
                ('updated_price', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('NEW ARRIVALS', 'N ARRIVALS'), ('ORGANIC FOOD', 'ORGANIC FOOD'), ('BEST SELLING PRODUCTS', 'BEST SELLING PRODUCTS'), ('TOP RATED PRODUCTS', 'TOP RATED PRODUCTS'), ('KHILMAR', 'KHILMAR'), ('JILBAB', 'JILBAB'), ('ABAYA/BORKA', 'ABAYA/BORKA'), ('LINEN', 'LINEN'), ('COTTON', 'COTTON'), ('CAPE', 'CAPE'), ('NIQAB', 'NIQAB'), ('HAND GLOVES & SOCKS', 'HAND GLOVES & SOCKS'), ('SUNNAH ITEM', 'SUNNAH ITEM'), ('ORGANIC FOOD', 'ORGANIC FOOD')], default=('NEW ARRIVALS', 'N ARRIVALS'), max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='slider_images')),
            ],
        ),
    ]
