# Generated by Django 3.2.4 on 2021-06-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('NEW ARRIVALS', 'NEW ARRIVALS'), ('ORGANIC FOOD', 'ORGANIC FOOD'), ('BEST SELLING PRODUCTS', 'BEST SELLING PRODUCTS'), ('TOP RATED PRODUCTS', 'TOP RATED PRODUCTS'), ('KHILMAR', 'KHILMAR'), ('JILBAB', 'JILBAB'), ('ABAYA/BORKA', 'ABAYA/BORKA'), ('LINEN', 'LINEN'), ('COTTON', 'COTTON'), ('CAPE', 'CAPE'), ('NIQAB', 'NIQAB'), ('HAND GLOVES & SOCKS', 'HAND GLOVES & SOCKS'), ('SUNNAH ITEM', 'SUNNAH ITEM'), ('ORGANIC FOOD', 'ORGANIC FOOD')], default=('NEW ARRIVALS', 'NEW ARRIVALS'), max_length=200),
        ),
    ]
