# Generated by Django 3.2.4 on 2021-06-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='updated_price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
